name: 'Run Tests'
on:
  push:
    branches:
      - 'master'
      - 'new-auto-updater'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tag-release:
    name: 'Tag Release and Bump Dependents'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          # fetch-depth 0 means deep clone the repo
          fetch-depth: 0
      - name: 'Update Version'
        id: version
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
          version=v"$(cat package/version)"
          git tag --delete "${version}" || true
          git push --delete origin "${version}" || true
          git tag "${version}" HEAD
          git push origin "${version}:${version}"
          echo "::set-output name=version::$(cat package/version)"

  call-auto-update:
    name: 'Invoke the auto-updater'
    needs: tag-release
    runs-on: ubuntu-latest
    uses: runtimeverification/devops/.github/workflows/update-deps.yml@master
    with:
      repo: runtimeverification/pyk
      version: ${{ needs.tag-release.outputs.version }}
