name: 'Run Tests'
on:
  push:
    branches:
      - 'automate-release'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tag-release:
    name: 'Tag Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          # fetch-depth 0 means deep clone the repo
          fetch-depth: 0
      - name: 'Update Version'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
          old_tag=$(git describe --tags | cut --delimiter='-' --field='1')
          tag_base=$(echo ${old_tag} | sed 's/\(v[0-9]*\.[0-9]*\.\)\([0-9]*\)/\1/')
          tag_tail=$(echo ${old_tag} | sed 's/\(v[0-9]*\.[0-9]*\.\)\([0-9]*\)/\2/')
          tag_tail=$(echo "1 + ${tag_tail}" | bc)
          new_tag="${tag_base}${tag_tail}"
          git tag "${new_tag}" HEAD
          git push origin --tags

  bump-dependents:
    name: 'Bump Dependents'
    runs-on: ubuntu-latest
    needs: [tag-release]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          # fetch-depth 0 means deep clone the repo
          fetch-depth: 0
      - name: 'Update dependents'
        env:
          JENKINS_DEVOPS_TOKEN: ${{ secrets.JENKINS_DEVOPS_TOKEN }}
        run: |
          git fetch --tags
          version=$(git describe HEAD)
          curl --fail 'https://ci.runtimeverification.com/jenkins/buildByToken/buildWithParameters' \
              --data job=Devops/master                                                              \
              --data token=${JENKINS_DEVOPS_TOKEN}                                                  \
              --data UPDATE_DEPS=true                                                               \
              --data UPDATE_DEPS_REPO=runtimeverification/pyk                                       \
              --data UPDATE_DEPS_VERSION=${version}

