name: 'Run PR Tests'
on:
  pull_request:
  workflow_dispatch:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality-checks:
    name: 'Code Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Run code quality checks'
        run: make check
      - name: 'Run pyupgrade'
        run: make pyupgrade

  unit-tests:
    needs: code-quality-checks
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Run unit tests'
        run: make cov-unit

  profile:
    needs: code-quality-checks
    name: 'Profiling'
    runs-on: [self-hosted, linux, normal-ephemeral]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
      - name: 'Install Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Install K'
        run: |
          K_VERSION=$(cat deps/k_release)
          DEB_PACKAGE_NAME=kframework_${K_VERSION}_amd64_ubuntu_jammy.deb
          wget https://github.com/runtimeverification/k/releases/download/v${K_VERSION}/${DEB_PACKAGE_NAME}
          sudo apt-get update
          sudo apt-get -y install ./${DEB_PACKAGE_NAME}
          kompile --version
      - name: 'Run profiling'
        run: |
          make profile
          find /tmp/pytest-of-${USER}/pytest-current/ -type f -name '*.prof' | sort | xargs tail -n +1
